EvidenceMHD/urls.py
from django.contrib import admin
from django.urls import path
from evidence import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('depart/<int:depart_id>/', views.depart, name='depart'),
    path('depart/<int:depart_id>/addcomment', views.addcomment, name='addcomment'),
    path('depart/search/<str:word>/<int:sid1>.<int:sid2>', views.departlivesearch, name='departlivesearch'),
    path('depart/search', views.departsearch, name='departsearch'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user/search', views.usersearch, name='usersearch'),
    path('stop/search', views.stopsearch, name='stopsearch'),
    path('vehicle/<int:vehicle_id>/', views.vehicle, name='vehicle'),
    path('vehicle/search', views.vehiclesearch, name='vehiclesearch'),
    path('vehicle/types', views.vehicletypes, name='vehicletypes'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

evidence/models.py
from django.db import models

class Manufacturer(models.Model):
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return self.name

class VehicleType(models.Model):
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.RESTRICT)
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return f'{self.manufacturer} {self.name}'

class Carrier(models.Model):
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return self.name

class Vehicle(models.Model):
    carrier = models.ForeignKey(Carrier, on_delete=models.RESTRICT)
    type = models.ForeignKey(VehicleType, on_delete=models.RESTRICT)
    reg_num = models.CharField(max_length=7)
    state = models.SmallIntegerField()
    datetime_added = models.DateTimeField('date added', auto_now_add=True)
    manufactured_year = models.SmallIntegerField(null=True, blank=True)
    last_seen = models.DateTimeField('last seen date', null=True, blank=True)
    SPZ = models.CharField(max_length=7, null=True, blank=True)
    
    def __str__(self):
        return self.reg_num
    
class Stop(models.Model):
    name = models.CharField(max_length=64)
    
    def __str__(self):
        return self.name
    
class Depart(models.Model):
    first_stop = models.ForeignKey(Stop, on_delete=models.RESTRICT, related_name='fstop')
    actual_stop = models.ForeignKey(Stop, on_delete=models.RESTRICT, related_name='astop')
    last_stop = models.ForeignKey(Stop, on_delete=models.RESTRICT, related_name='lstop')
    first_vehicle = models.ForeignKey(Vehicle, on_delete=models.RESTRICT)
    line = models.CharField(max_length=6)
    route = models.IntegerField()
    date = models.DateField(auto_now_add=True)
    datetime_start = models.DateTimeField(auto_now_add=True)
    datetime_actual = models.DateTimeField(auto_now_add=True)
    actual_delay = models.IntegerField(null=True, blank=True)
    
    def __str__(self):
        return f'{self.line}/{self.route} on {self.date.strftime("%d.%m.%Y")}'
    
class User(models.Model):
    username = models.CharField(max_length=24)
    email = models.EmailField(max_length=320)
    role = models.SmallIntegerField(default=0)
    password_hash = models.CharField(max_length=256)
    last_login = models.DateTimeField(auto_now_add=True)
    #authenticated = db.Column(db.Boolean, default=False)

    USERNAME_FIELD = 'email'

    def is_active(self):
        return True
    
    def get_id(self):
        return self.email
    
    is_authenticated = True

    def is_anonymous(self):
        # False as we do not support annonymity
        return False
    
    def __str__(self):
        return f'{self.username}'
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    depart = models.ForeignKey(Depart, on_delete=models.CASCADE)
    datetime_added = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    
    def __str__(self):
        return f'{self.user.username} -> {self.depart} wrote {self.content}'
    
class SetVehicle(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.RESTRICT)
    depart = models.ForeignKey(Depart, on_delete=models.CASCADE)
    position = models.SmallIntegerField()
    
    def __str__(self):
        return f'{self.vehicle} in {self.depart}'
    
class RegNumberHistory(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    date_valid_from = models.DateTimeField()
    date_valid_to = models.DateTimeField(auto_now_add=True)
    reg_num = models.CharField(max_length=7)
    
    def __str__(self):
        return f'{self.vehicle.reg_num} was {self.reg_num}'
    
# python manage.py makemigrations evidence
# python manage.py migrate
# python manage.py runserver

# python manage.py shell

# d1 = Depart.objects.get(pk=1)
# Comment.objects.filter(depart=d1)
# d1.comment_set.all()
# d1.comment_set.filter(content__contains='first')

evidence/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import UserCreationForm
from .models import Comment, User, Carrier, VehicleType

# + depart search form (using Ajax and JS)

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=200, label='Username')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise forms.ValidationError('Invalid login name or password.')

        if not check_password(password, user.password_hash):
            raise forms.ValidationError('Invalid login name or password.')

        cleaned_data['user'] = user
        return cleaned_data

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class UserSearchForm(forms.Form):
    username = forms.CharField(label="Username", max_length=24, required=False)


class StopSearchForm(forms.Form):
    name = forms.CharField(label="Name", max_length=64, required=False)

class VehicleSearchForm(forms.Form):
    reg_num = forms.CharField(label="Reg. num", max_length=7, required=False)
    carrier = forms.ModelChoiceField(queryset=Carrier.objects.all(), required=False)
    type = forms.ModelChoiceField(queryset=VehicleType.objects.all(), required=False)

evidence/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth import authenticate
from .models import Depart, Comment, User, SetVehicle, Vehicle, RegNumberHistory, Stop, VehicleType
from .forms import CommentForm, UserRegistrationForm, UserSearchForm, StopSearchForm, VehicleSearchForm, UserLoginForm


def index(request):
    departs = Depart.objects.all()
    users = User.objects.all()
    vehicles = Vehicle.objects.all()
    comments = Comment.objects.all()

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None
    
    return render(request, 'evidence/index.html', {'user': user, 'departs': len(departs), 'users': len(users), 'vehicles': len(vehicles), 'comments': len(comments)})


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                request.session['user'] = user.id
                return redirect('index')
            else:
                form.add_error(None, 'Invalid login')
    else:
        form = UserLoginForm()

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None

    return render(request, 'evidence/login.html', {'user': user, 'form': form})


def logout(request):
    try:
        del request.session['user']
    except KeyError:
        pass
    return render(request, 'evidence/logout.html', {'user': None})


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = User()
            user.username = form.data.get('username')
            user.email = form.data.get('email')
            user.password_hash = make_password(form.data.get('password1'))
            user.save()

            messages.success(request, f'Your account has been created. You can log in now!')    
            return redirect('index')
    else:
        form = UserRegistrationForm()

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None

    return render(request, 'evidence/register.html', {'user': user, 'form': form})


def depart(request, depart_id):
    depart = get_object_or_404(Depart, pk=depart_id)
    comments = Comment.objects.filter(depart=depart)
    sets = SetVehicle.objects.filter(depart=depart)
    comment_form = CommentForm()

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None
    
    return render(request, 'evidence/depart.html', {'user': user, 'user': user, 'depart': depart, 'comments': comments, 'sets': sets, 'comment_form': comment_form})


def departsearch(request):

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None
    
    return render(request, 'evidence/departsearch.html', {'user': user})


def departlivesearch(request, word, sid1, sid2):
    departs = Depart.objects.filter(line__icontains=word)

    """
    if len(departs) > 0:
        response = ''
        for d in departs:
            response += f'{reverse("depart", args=(d.id,))},{d.line},{d.route},{d.date.strftime("%d.%m.%Y")}|'
    else:
        response = ''
    """
    
    return render(request, 'evidence/departlivesearch.html', {'departs': departs})


def addcomment(request, depart_id):
    depart = get_object_or_404(Depart, pk=depart_id)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            try:
                user = User.objects.get(pk=request.session['user'])
            except User.DoesNotExist and KeyError:
                user = None
    
            if user == None:
                messages.error(request, "You need to be logged in to add message!")
                return redirect('depart', depart_id=depart_id)

            comment_content = comment_form.cleaned_data['content']
            
            comment = Comment(depart=depart, content=comment_content, user=user)
            comment.save()
            
            return redirect('depart', depart_id=depart_id)


def user(request, user_id):
    user2 = get_object_or_404(User, pk=user_id)
    comments = Comment.objects.filter(user=user2)

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None
    
    return render(request, 'evidence/user.html', {'user': user, 'user2': user2, 'comments': comments})


def usersearch(request):

    users = None
    if request.method == 'POST':
        form = UserSearchForm(request.POST)
        if form.is_valid():
            users = User.objects.filter(username__icontains=form.cleaned_data['username'])

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None

    form = UserSearchForm()
    return render(request, 'evidence/usersearch.html', {'user': user, 'users': users, 'form': form})

def stopsearch(request):

    stops = None
    if request.method == 'POST':
        form = StopSearchForm(request.POST)
        if form.is_valid():
            stops = Stop.objects.filter(name__icontains=form.cleaned_data['name'])

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None

    form = StopSearchForm()
    return render(request, 'evidence/stopsearch.html', {'user': user, 'stops': stops, 'form': form})


def vehicle(request, vehicle_id):
    vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
    sets = SetVehicle.objects.filter(vehicle=vehicle)
    reg_nums = RegNumberHistory.objects.filter(vehicle=vehicle)

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None
    
    return render(request, 'evidence/vehicle.html', {'user': user, 'vehicle': vehicle, 'sets': sets, 'reg_nums': reg_nums})

def vehiclesearch(request):

    vehicles = None
    if request.method == 'POST':
        form = VehicleSearchForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data['reg_num'] if form.cleaned_data['reg_num'] is not None else "Noooone")
            c_valid = Q(carrier=form.cleaned_data['carrier']) if form.cleaned_data['carrier'] is not None else Q(pk__gt=0)
            t_valid = Q(type=form.cleaned_data['type']) if form.cleaned_data['type'] is not None else Q(pk__gt=0)
            r_valid = Q(reg_num__icontains=form.cleaned_data['reg_num']) if len(form.cleaned_data['reg_num']) != 0 else Q(pk__gt=0)
            vehicles = Vehicle.objects.filter(c_valid & t_valid & r_valid)

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None

    form = VehicleSearchForm()
    return render(request, 'evidence/vehiclesearch.html', {'user': user, 'vehicles': vehicles, 'form': form})

def vehicletypes(request):
    veh_types = VehicleType.objects.all().order_by('manufacturer')

    try:
        user = User.objects.get(pk=request.session['user'])
    except User.DoesNotExist and KeyError:
        user = None

    return render(request, 'evidence/vehtypes.html', {'user': user, 'veh_types': veh_types})

templates/evidence/base.html
{% load static %}
<html>
  <head>
    {% load bootstrap5 %} 
    {% bootstrap_css %} 
    {% bootstrap_javascript %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'evidence/style.css' %}">

    {% block head %}
    <title>Default</title>
    {% endblock %}
  </head>
  <body class='dark-mode-body' data-bs-theme="dark">
    {% include 'evidence/messages.html' %}

    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">My Website</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'departsearch' %}">DEPARTS</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'vehiclesearch' %}">VEHICLES</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'vehicletypes' %}">VEH.TYPES</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'usersearch' %}">USERS</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'stopsearch' %}">STOPS</a>
                  </li>
                  {% if user.is_authenticated %}
                    <li class="nav-item user">
                      <div class="dropdown">
                          <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                          </a>
                          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                              <li><a class="dropdown-item" href="{% url 'user' user.id %}">Profile</a></li>
                              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                          </ul>
                      </div>
                    </li>
                  {% else %}
                    <li class="nav-item user">
                      <a class="nav-link" href="{% url 'login' %}">Login/Register</a>
                    </li>
                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main class="container mt-4">
      {% block body %}
      {% endblock %}
    </main>
    <script>
        // Toggle dark mode
        const body = document.querySelector('body');
        const toggleDarkMode = () => {
            body.classList.toggle('dark-mode');
        };
    </script>
  </body>
</html>

templates/evidence/depart.html
{% extends "evidence/base.html" %} 
{% block body %}
<div class="card darker-mode p-3 m-3">
  <h2>Depart</h2>

  <p>Line/route: {{ depart.line}}/{{depart.route}} at {{ depart.date|date:"d.m.Y" }}</p>
  <p>
    First stop: {{ depart.first_stop }} at {{ depart.datetime_start|date:"d.m.Y H:i" }}
  </p>
  <p>
    Actual stop: {{ depart.actual_stop }} at {{ depart.datetime_actual|date:"d.m.Y H:i" }} with {{ depart.actual_delay}}min delay
  </p>
  <p>Last stop: {{ depart.last_stop }}</p>
  <p>Vehicle: <a href="{% url 'vehicle' depart.first_vehicle.id %}">{{ depart.first_vehicle.type.manufacturer }} {{ depart.first_vehicle.type }} reg. num. {{ depart.first_vehicle.reg_num }} ran by {{ depart.first_vehicle.carrier}}</a></p>
</div>

<div class="card darker-mode p-3 m-3">
  <h3>Vehicles in set</h3>

    <ul class="list-group">
        {% for set in sets %}
            <li role="button" class="list-group-item dark-mode"  onclick="location.href = '{% url 'vehicle' set.vehicle.id %}'">{{ set.position }}. {{ set.vehicle}}</li>
        {% endfor %}
    </ul>
</div>

<div class="card darker-mode p-3 m-3">
  <h3>Comment section {{ user2.username }}</h3>
  {% for comment in comments %}
      <div class="col">
      <div class="card mb-3 dark-mode">
          <div class="card-body">
          <p class="card-text">{{ comment.content}}</p>
          </div>
          <div class="card-footer">
          <small class="text-muted">Posted by <a href="{% url 'user' comment.user.id %}">{{ comment.user.username}}</a> at {{comment.datetime_added|date:"d.m.Y H:i"}}</small>
          </div>
      </div>
      </div>
  {% endfor %}
</div>

<div class="card darker-mode p-3 m-3">
  <h3>Add comment</h3>

  <form method="post" action="{% url 'addcomment' depart.id %}">
    {% csrf_token %} {{ comment_form.as_p }}
    <input type="submit" value="Submit" />
  </form>
</div>
{% endblock %}

templates/evidence/departlivesearch.html

{% for depart in departs %}
    <li class="list-group-item dark-mode" role="button" onclick="location.href = '{% url 'depart' depart.id %}'">{{depart.line}}/{{depart.route}} at {{depart.date|date:"d.m.Y"}}</li>
{% endfor %}

templates/evidence/departsearch.html

{% extends "evidence/base.html" %} 
{% load static %}
{% block head %}
<script type="text/javascript" src="{% static 'evidence/departsearch.js' %}"
></script>
<style type="text/css">
  #livesearch {
    margin: 0px;
    width: 194px;
  }
  #txt1 {
    margin: 0px;
  }
</style>
<title>Departs</title>
{% endblock %}

{% block body %}

<div class="container mt-5">
    <div class="d-flex justify-content-center">    
        <div class="col-sm-6">
            <h1>Depart search</h1>
            <form class="mb-3">
              <input type="text" class="form-control" id="txt1" size="30" onkeyup="showResult(this.value)" placeholder="Type to search..." />  
            </form>
            <hr>
            <ul class="list-group" id="livesearch">
            </ul>
        </div>
    </div>
</div>

{% endblock %}

templates/evidence/index.html
{% extends "evidence/base.html" %} 
{% block head %}
<title>SKJ</title>
{% endblock %} 
{% block body %}

<h1>Welcome to this site with a name!</h1>
<p>This is a project to SKJ by Jakub Koběrský, KOB0070</p>

<hr>

<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card card-dark">
            <div class="card-body">
                <h5 class="card-title">Users Registered</h5>
                <p class="card-text">{{ users }}</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card card-dark">
            <div class="card-body">
                <h5 class="card-title">Departs recorded</h5>
                <p class="card-text">{{ departs }}</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card card-dark">
            <div class="card-body">
                <h5 class="card-title">Comments written</h5>
                <p class="card-text">{{ comments }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/evidence/login.html
{% extends "evidence/base.html" %}
{% block head %}
<title>Login</title>
<style>
  .login-form {
      background-color: #222;
      margin: 0 auto;
      max-width: 400px;
      padding: 2rem;
      border-radius: 5px;
      box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
  }

  .login-form label {
      font-weight: bold;
  }
</style>
{% endblock %} 


{% block body %}
<div class="login-form">
  <h1 class="text-center mb-4">Login</h1>
  <p>Don't have an account? <a href="{% url 'register' %}">Register here</a>!</p>
  <form action="" method="POST">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field, errors in form.errors.items %}
            {% for error in errors %}
                {{ error }}
            {% endfor %}
        {% endfor %}
    </div>
    {% endif %}
    <div class="mb-3">
        <label for="id_username" class="form-label">Username</label>
        <input type="text" class="form-control" name="username" maxlength="200" required="" id="id_username">
    </div>
    <div class="mb-3">
        <label for="id_password" class="form-label">Password</label>
        <input type="password" class="form-control" name="password" required="" id="id_password">
    </div>
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
  </form>
</div>

{% endblock %}

templates/evidence/logout.html
{% extends 'evidence/base.html' %} {% block body %}
<br />
<div class="alert alert-success" role="alert">
  <h2 style="text-align: center">Logged out!</h2>
</div>

<h3>Login again?</h3>
<a href="{% url 'login' %}">---> Login</a> <br />
<a href="{% url 'index' %}"><--- Or go back to home.</a>
{% endblock %}

templates/evidence/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

templates/evidence/register.html
{% extends "evidence/base.html" %} 
{% block head %}
<title>Register</title>
<style>
  .login-form {
      background-color: #222;
      margin: 0 auto;
      max-width: 400px;
      padding: 2rem;
      border-radius: 5px;
      box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
  }

  .login-form label {
      font-weight: bold;
  }
</style>
{% endblock %} 

{% block body %}
<div class="login-form">
  <h1 class="text-center mb-4">Register</h1>
  <p>Already have an account? <a href="{% url 'login' %}">Login here</a>!</p>
  <form action="" method="POST">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field, errors in form.errors.items %}
            {% for error in errors %}
                {{ error }}<br>
            {% endfor %}
        {% endfor %}
    </div>
    {% endif %}
    <div class="mb-3">
        <label for="id_username" class="form-label">Username</label>
        <input type="text" class="form-control" name="username" maxlength="24" required="" id="id_username">
    </div>
    <div class="mb-3">
        <label for="id_email" class="form-label">Email</label>
        <input type="email" class="form-control" name="email" maxlength="320" autofocus="" required="" id="id_email">
    </div>
    <div class="mb-3">
        <label for="id_password1" class="form-label">Password</label>
        <input type="password" class="form-control" name="password1" autocomplete="new-password" required="" id="id_password1">
        <div id="emailHelp" class="form-text">Don't worry. We're hashing your password.</div>
    </div>
    <div class="mb-3">
        <label for="id_password2" class="form-label">Password confirmation</label>
        <input type="password" class="form-control" name="password2" autocomplete="new-password" required="" id="id_password2">
    </div>
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">Register</button>
    </div>
  </form>
</div>

{% endblock %}

templates/evidence/stopsearch.html
{% extends "evidence/base.html" %} 
{% block head %}
<title>Stops</title>
{% endblock %}

{% block body %}

<div class="container mt-5">
    <div class="d-flex justify-content-center">    
        <div class="col-sm-6">
            <h1>List of stops</h1>
            <form class="mb-3" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search stops..." name="name" maxlength="64" id="id_name">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </form>
            <hr>
            <ul class="list-group">
                {% for stop in stops %}
                    <li class="list-group-item dark-mode">{{ stop.name }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

templates/evidence/user.html
{% extends "evidence/base.html" %} 
{% block head %}
<title>User {{ user2.username }}</title>
{% endblock %}

{% block body %}
<div class="d-flex justify-content-center">  
    <div class="col-sm-6">
        <div class="card darker-mode p-3 m-3">
            <h2>User {{ user2.username }}</h2>
            <label>{{ user2.email }}</label>
        </div>
        
        <div class="card darker-mode p-3 m-3">
            <h3>Comments posted by {{ user2.username }}</h3>
            {% for comment in comments %}
                <div class="col">
                <div class="card mb-3 dark-mode">
                    <div class="card-body">
                    <p class="card-text">{{ comment.content}}</p>
                    </div>
                    <div class="card-footer">
                    <small class="text-muted">Posted to <a href="{% url 'depart' comment.depart.id %}">{{ comment.depart}}</a> on {{comment.datetime_added|date:"d.m.Y H:i"}}</small>
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/evidence/vehtypes.html

{% extends "evidence/base.html" %} 
{% block head %}
<title>Vehicle types</title>
{% endblock %}

{% block body %}

<div class="container mt-5">
    <div class="d-flex justify-content-center">    
        <div class="col-sm-6">
            <h1>List of vehicle types</h1>
            <hr>
            <ul class="list-group">
                {% for veh_type in veh_types %}
                    <li class="list-group-item dark-mode">{{ veh_type }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}